language = "Javascript"
version = "20.9.0"
compiled = false
extension = "js"
environment = [
    "PATH=/opt/node/20.9.0/bin",
    "NODE_PATH=/usr/local/lib/node_modules",
]
build_command = []
run_command = ["/opt/node/20.9.0/bin/node", "{file}"]
test_file = "test.js"
aliases = ["javascript", "js"]
should_limit_memory = true
memory_limit = 2048
process_limit = 2048
allowed_entrypoints = 1
